### ISSUE TITLE
почему опенжл это же кросплатнформена

### ISSUE THREAD

**Issue by tupoy-ya** [Publisher29/game_novel_by_gypsies_2001#2]
надоиспол ьзавать прямойХ это важно
и ещё надо использовать visual c# += это очень важнр
переписывай

**Comment by Publisher29** [comment]
Ты шо блять ахуела?!?!!?!?!?!
Ща как кок отрежу и будет тебе анивизуал c# += важнр

**Comment by tupoy-ya** [comment]
> Ты шо блять ахуела?!?!!?!?!?! Ща как кок отрежу и будет тебе анивизуал c# += важнр
![nazar](https://user-images.githubusercontent.com/72797377/164218165-d4fe2c1e-ce9d-419c-8d26-8ca9b150f99d.gif)
